### ISSUE TITLE
Question about Instances and detection of multiple objects

### ISSUE THREAD

**Issue by gyNancy** [alexriedel1/detectron2-GradCAM#1]
Hi,

Really like your framework for explaining detectron2. I'm new to gradcam. 

So I imported my own model which detects multiple website UI elements (for example, logo (class=1), input boxes(class = 0) ). I don't quite understand what you mean by gradcam is explaining per object but not per class. I set instance = 1 in the code and does that mean gradcam will show important features for class 1? However, in my experiments, gradcam shows important features (heatmap) for either only logo (class 1) or input boxes (class 0). Is it supposed to be working in this way? If I only want it to show important features for the input box, can I modify the code to do that? 

Thanks!

**Comment by alexriedel1** [comment]
Hi!
Assuming you are using a object detection algorithm like Faster R-CNN, the CAM generation per instance mean, that the backpropagation is done for the n-th detected object instance. 

Example:
If you're detection result is 4 objects of 2 classes:
```
[
"class_0" : [x1, x2, y1, y2], 
"class_1" : [x1, x2, y1, y2], 
"class_1" : [x1, x2, y1, y2], 
"class_0" : [x1, x2, y1, y2]
]
```
and select the 3rd object instance (`"class_1" : [x1, x2, y1, y2],`) for Grad-CAM backprop, you will get the heatmap explaining the important regions for this single object instance prediction.

**Comment by gyNancy** [comment]
Thanks for your explanations and now I understand the logic. I select the instance for my targeted class and solve the problem.
